baseURL = "https://www.equitynminsights.com/"
languageCode = "en-us"
title = "Equity New Mexico Insights"

[params]
  logo = "/images/logo.png"
  name = "Equity New Mexico Real Estate"
  description = "Market updates and real estate news for NM."

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Market Updates"
    url = "/blog/"
    weight = 2
